/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.5.1/userguide/multi_project_builds.html
 */

rootProject.name = "kotlin-lambda-example-jvm"

pluginManagement {
    plugins {
        id("org.jetbrains.kotlin.jvm") version "1.7.20" apply (false)
    }
}
include(":products")
project(":products").projectDir = file("software/products")